### ISSUE TITLE
wrong Demo user in README.md

### ISSUE THREAD

**Issue by tanasatit** [tarothanawat/ku-polls#61]
<img width="500" alt="image" src="https://github.com/user-attachments/assets/5ab1ddf4-66e6-4afc-8c2e-3990d6c82f27">
Unable to log in with the username provided.

**Comment by tarothanawat** [comment]
In the Readme.md file I typed Demo1 instead of demo1 (case sensitive). Thanks for your help!
![image](https://github.com/user-attachments/assets/d2d0dbe6-f7e1-4602-ac34-315567073bb9)
